SELECT DISTINCT
    P.IDACTIVITY,
    P.NMACTIVITY,
    ST.idstruct
FROM
    PMSTRUCT ST
    LEFT JOIN GNFORMULA FORM ON ST.cdformulaexecutor = FORM.CDFORMULA
    LEFT JOIN PMPROCESS A ON ST.CDPROC = A.FGPROCESSMODEL
    LEFT JOIN PMACTIVITY P ON P.CDACTIVITY = ST.CDPROC
WHERE
    ST.cdformulaexecutor IS NOT NULL
    AND FORM.txcompiled LIKE '%' || 'defineExecutor' || '%'