SELECT
    ,PROCESSO.IDPROCESS
    ,PROCESSO.NMPROCESS
    ,STC03.IDSOLICITACAO
    ,STC03.NMSOLICITANTE
    ,STC03.NMAREAENV
    ,PESQ.PESQSAT
    ,PESQ.FGPESQUISA    
    ,PESQ.OBSERVACOES
    ,PESQ.IDSOL
    ,GRS.CDREVISIONSTATUS AS IDSITUACAO,
    ,GRS.NMREVISIONSTATUS AS NMSITUACAO
FROM DYNGTISTC03 STC03
LEFT JOIN DYNSTC03PESQSAT PESQ ON PESQ.OIDENTITYREG = STC03.OID
LEFT JOIN GNASSOCFORMREG ASSOCPROC ON ASSOCPROC.OIDENTITYREG = STC03.OID
LEFT JOIN WFPROCES PROCESSO ON PROCESSO.CDASSOCREG = ASSOCPROC.CDASSOC
LEFT JOIN GNREVISIONSTATUS GRS ON GRS.CDRESVISIONSTATUS = PROCESSO.CDSTATUS
LEFT JOIN DYNGTISTC03NMSOLICITANTE SOLI ON SOLI.OID = STC03.OIDABCPZVYF0H1X6Q
LEFT JOIN DYNGTISTC03NMAREASENV AREA ON AREA.OID = STC03.OIDABCX1JH3YQKX0K6
LEFT JOIN WFSTRUCT WFSATIVIDADE ON WFSATIVIDADE.IDPROCESS= PROCESSO.IDOBJECT AND WFSATIVIDADE.FGTYPE IN(2,3) AND WFSATIVIDADE.FGSTATUS = 2         
LEFT JOIN WFACTIVITY WFAATIVIDADE ON WFSATIVIDADE.IDOBJECT= WFAATIVIDADE.IDOBJECT
