SELECT
    PESQ.IDSOL,
	WFP.NMPROCESS AS TITULO,
	STC03.NMTITULOMELHORI AS NM_TITULO_MELHORIA,
    STC03.TXMATSOLICITLOG	AS MAT_SOLICITANTE,
	STC03.NMSOLICITANTE	AS NM_SOLICITANTE,
    STC03.NMAREAENV			AS DS_AREA_SOLICITACAO,
    PESQ.PESQSAT,
    PESQ.FGPESQUISA,
    STC03.DTINICIO	AS DT_SOLICITACAO
    ,(WFP.DTSTART || '' || WFP.TMSTART::TIME)   AS DT_INICIO
	,(WFP.DTFINISH || '' || WFP.TMFINISH::TIME)    AS DT_FIM
	,WFP.FGSTATUS AS IDSITUATION
	,CASE WFP.FGSTATUS 
		WHEN 1 THEN '#{103131}' -- EM ANDAMENTO
		WHEN 2 THEN '#{107788}' -- SUSPENSO
		WHEN 3 THEN '#{104230}'	-- CANCELADO	 
		WHEN 4 THEN '#{100667}' -- ENCERRADO
		WHEN 5 THEN '#{200712}' -- BLOQUEADO PARA EDIÇÃO
		END AS SITUATION --STATUS PROCESSO 
				
	,GRS.CDREVISIONSTATUS	-- ID SITUAÇÃO DO WORKFLOW
	,GRS.NMREVISIONSTATUS 	-- SITUAÇÃO DO WORKFLOW (NOME)

FROM DYNGTISTC03 STC03
INNER JOIN	GNASSOCFORMREG ASSOCPROC  ON ASSOCPROC.OIDENTITYREG = STC03.OID           
INNER JOIN	WFPROCESS WFP ON WFP.CDASSOCREG = ASSOCPROC.CDASSOC AND WFP.IDPROCESSMODEL = 'GTI-STC03'
LEFT JOIN   DYNGTISTC03PESQSAT PESQ ON PESQ.IDSOL = STC03.IDSOLICITACAO
LEFT JOIN	DYNGTISTC03STATUSM STATUS ON STC03.OIDABCSMVNDUQM4IRF = STATUS.OID
LEFT JOIN	GNREVISIONSTATUS GRS ON GRS.CDREVISIONSTATUS = WFP.CDSTATUS