SELECT * FROM (
	WITH DADOS_SOLICITACAO AS (	
		SELECT 	WFP.IDPROCESS AS ID
				,WFP.NMPROCESS AS TITULO
				
				--Dados do formulário de Solicitação
				
				,TIPOSIS.DSTIPOMELHORIA	AS DS_TIPO_SISTEMA
				,STC03.DTINICIO	AS DT_SOLICITACAO
				--Envolvidos / Responsáveis
				,STC03.TXMATSOLICITLOG	AS MAT_SOLICITANTE
				,STC03.NMSOLICITANTE	AS NM_SOLICITANTE
				,STC03.IDANLNEGOCIO	AS MAT_ANALISTA_NEG_TI
				,STC03.NMANLNEGOCIO		AS NM_ANALISTA_NEG_TI
				,STC03.IDMATRICULAGEST	AS MAT_GESTOR_AREA
				,STC03.NMSUPAREAENV		AS NM_GESTOR_AREA
				,STC03.NMAREAENV			AS DS_AREA_SOLICITACAO			
				,STC03.NMTITULOMELHORI::VARCHAR(255) AS NM_PROCESSO_MELHORIA
				,STC03.NMAREASENV		AS TX_AREAS_ENVOLVIDAS_RPA
				,CASE STC03.FGIMPACTFIN WHEN 1 THEN 'SIM' ELSE 'NAO' END AS NM_IMPACTFIN
				,CASE STC03.FGALTERADO6M WHEN 1 THEN 'SIM' ELSE 'NAO' END AS NM_ALTERA6M
				,CASE STC03.FGFERRAMENTAESP WHEN 1 THEN 'SIM' ELSE 'NAO' END AS NM_USAFERRAMENTAESPEC
				,STC03.VLTEMPREPETE AS VL_TEMPREPETE -- Entra no Calculo de Estimativas
				,STC03.VLTEMPEXECUTE AS VL_TEMPEXECUTE -- Entra no Calculo de Estimativas
				,CASE STC03.FGPROCESSOMANU WHEN 1 THEN 'SIM' ELSE 'NAO' END AS NM_PROCESSOMANUAL_RPA
				,CASE STC03.FGPROCESSONOVO WHEN 1 THEN 'SIM' ELSE 'NAO' END AS NM_PROCESSONOVO_RPA
				,STC03.TXCOMOEFEITOATU AS TX_COMO_FEITO_ATUALMENTE_RPA
				,STC03.TXPASSOPASSOBOT AS TX_PASSO_PASSO_BOT
				,STC03.TXCOMOSERAUSADO AS TX_COMO_SERA_USADO
				,STC03.TXJUSTIFICATIVA 	AS TX_JUSTIFICATIVA		
				,STC03.VLCUSTO			AS VL_CUSTO
				,GRAUIMP.dsgrauimpacto		AS DS_GRAU_IMPACTO
				,COALESCE(STATUS.dssstatusmelhor,'')		AS STATUSMELHOR	

				
				-- Dados gerais do WORKFLOW
				,(WFP.DTSTART + WFP.TMSTART::TIME) 	AS DT_INICIO
				,(WFP.DTFINISH + WFP.TMFINISH::TIME)	AS DT_FIM		
				
				,WFP.FGSTATUS AS IDSITUATION
				,CASE WFP.FGSTATUS 
					WHEN 1 THEN '#{103131}' -- EM ANDAMENTO
					WHEN 2 THEN '#{107788}' -- SUSPENSO
					WHEN 3 THEN '#{104230}'	-- CANCELADO	 
					WHEN 4 THEN '#{100667}' -- ENCERRADO
					WHEN 5 THEN '#{200712}' -- BLOQUEADO PARA EDIÇÃO
				END AS SITUATION --STATUS PROCESSO 
				
				,GRS.CDREVISIONSTATUS	-- ID SITUAÇÃO DO WORKFLOW	
				,GRS.NMREVISIONSTATUS 	-- SITUAÇÃO DO WORKFLOW (NOME)

				-- ASSOCIAÇÕES AOS CAMPOS DE TABELAS DINÂMICAS  			
		  FROM	DYNGTISTC03 STC03
	INNER JOIN	GNASSOCFORMREG ASSOCPROC  ON ASSOCPROC.OIDENTITYREG = STC03.OID           
	INNER JOIN	WFPROCESS WFP ON WFP.CDASSOCREG = ASSOCPROC.CDASSOC AND WFP.IDPROCESSMODEL = 'GTI-STC03'
	LEFT JOIN	DYNGTISTC03TPMELHO TIPOSIS ON STC03.OIDABCWBJRFOOOZOE1 = TIPOSIS.OID
	LEFT JOIN  DYNGTISTC03GRAUDEI GRAUIMP ON STC03.OIDABCVMX6HV7YNBDK = GRAUIMP.OID
	LEFT JOIN	DYNGTISTC03STATUSM STATUS ON STC03.OIDABCSMVNDUQM4IRF = STATUS.OID
	LEFT JOIN	GNREVISIONSTATUS GRS ON GRS.CDREVISIONSTATUS = WFP.CDSTATUS
	)
		SELECT	*
		  FROM	DADOS_SOLICITACAO 
) B