SELECT
	WFP.IDPROCESS AS "ID Processo",
	WFP.NMPROCESS AS "Nome Processo",
	COALESCE(TABLE0.NMPRODUTO, TABLE0.NMPRODUTON) AS "Nome do Produto",
	(
		CASE
			WHEN WFP.FGCONCLUDEDSTATUS IS NOT NULL THEN CASE
				WHEN WFP.FGCONCLUDEDSTATUS = 1 THEN '#{100900}' -- EM DIA
				WHEN WFP.FGCONCLUDEDSTATUS = 2 THEN '#{100899}' -- EM ATRASO
			END
			ELSE -- COMO O SLA NÃO É CONFIGURADO EM 99% DOS WORKFLOWS, E QUANDO É CONFIGURADO, É ACIDENTALMETNE PELOS USUÁRIOS
			-- SUBSTITUÍ O CÓDIGO ABAIXO POR UMA VERSÃO MAIS PERFORMÁTICA SEM A NECESSIDADE DE SUBQUERIES EM CAMPOS DE SELECT.
			--CASE WHEN WFP.DTESTIMATEDFINISH IS NULL OR (WFP.DTESTIMATEDFINISH > (CAST(<!%TODAY%> AS DATE) + COALESCE((SELECT QTDAYS FROM ADMAILTASKEXEC WHERE CDMAILTASKEXEC = (SELECT TASK.CDAHEAD FROM ADMAILTASKREL TASK WHERE TASK.CDMAILTASKREL = (SELECT TBL.CDMAILTASKSETTINGS FROM CONOTIFICATION TBL))), 0)))
			CASE
				WHEN WFP.DTESTIMATEDFINISH IS NULL THEN '#{100900}' -- EM DIA
				WHEN (
					(
						WFP.DTESTIMATEDFINISH = CAST(cast(now() as date) AS DATE)
						AND WFP.NRTIMEESTFINISH >= (
							extract(
								'minute'
								FROM
									now()
							) + extract(
								'hour'
								FROM
									now()
							) * 60
						)
					)
					OR (
						WFP.DTESTIMATEDFINISH > CAST(cast(now() as date) AS DATE)
					)
				) THEN '#{201639}' -- PRÓXIMO DO VENCIMENTO
				ELSE '#{100899}' -- EM ATRASO
			END
		END
	) AS SLA,
	TO_TIMESTAMP(
		TO_CHAR(WFP.DTSTART, 'YYYY-MM-DD') || ' ' || WFP.TMSTART,
		'YYYY-MM-DD HH24:MI:SS'
	) AS "Data de Início",
	(
		CASE
			WFP.FGSTATUS
			WHEN 1 THEN '#{103131}' -- ANDAMENTO
			WHEN 2 THEN '#{107788}' -- SUSPENSO
			WHEN 3 THEN '#{104230}' -- CANCELADO
			WHEN 4 THEN '#{100667}' -- ENCERRADO
			WHEN 5 THEN '#{200712}' -- BLOQUEADO PARA EDIÇÃO
		END
	) AS "Situação do Processo",
	ADU.NMUSER AS SOLICITANTE,
	GNRS.IDREVISIONSTATUS,
	GNRS.NMREVISIONSTATUS,
	WFP.DTESTIMATEDFINISH + (WFP.NRTIMEESTFINISH * interval '1 minute') AS "Data de Deadline",
	WFP.IDREVISION AS "revisão",
	TO_TIMESTAMP(
		TO_CHAR(WFP.DTFINISH, 'YYYY-MM-DD') || ' ' || WFP.TMFINISH,
		'YYYY-MM-DD HH24:MI:SS'
	) AS "Data de Finalização",
	NULL AS "Data de SLA Finalizado",
	TABLE0.FGALTNORMA AS "Afeta atendimento da norma",
	TABLE0.FGALTCIRC AS "Alteração de Circuito Impresso",
	TABLE0.FGESQELETR AS "Alteração de Esquema Elétrico",
	TABLE0.FGAFETAAOI AS "Afeta AOI",
	TABLE0.FGALTETI AS "Alteração de Etiqueta",
	TABLE0.FGALTSTEN AS "Alteração Estêncil",
	TABLE0.FGALTISER AS "Alteração de Inserção",
	TABLE0.FGALTTRI AS "Alteração no TRI",
	TABLE0.FGALTMEC AS "Alteração Mecânica",
	TABLE0.FGALTPCM AS "Alterar Sucateamento",
	TABLE0.FGCATEGORIA AS Categoria,
	TABLE0.DTPREVIMPL AS "Data Prevista de Implantação",
	TABLE0.DTIMPLANT AS "Data de Implantação",
	TABLE0.DTDATA AS "Data da Solicitação",
	CAST(TABLE0.HRHORA AS NUMERIC(19)) * 1000 AS "Hora da Solicitação",
	TABLE0.IDETIQUETA AS "ID Etiqueta",
	TABLE0.IDGETORPROJETO AS "ID Gestor de Projeto",
	TABLE0.IDMEC AS "ID Mecânica",
	TABLE0.IDPED AS "ID PeD",
	TABLE0.IDSOLICITACAO AS "ID da Solicitação",
	TABLE0.NMMOTIVOALT AS "Motivo da Alteração",
	TABLE0.NMMOTIVO AS Motivo,
	TABLE0.CDPRODUTO AS "Código do Produto",
	TABLE0.NMGESTORPROJETO AS "Nome Gestor de Projeto",
	TABLE0.NMPED AS "Nome PeD",
	TABLE0.NOTIFICADOSSEG AS "Notificados Segmento",
	COALESCE(CAST(NRPO AS TEXT), NRPO2) AS PO,
	-- Irá mudar / Alteração Feita no Formulario
	TABLE0.FGTIPOPROD as "Tipo de Produto",
	TABLE0.FGTIPOSOLICITAC AS "Tipo de Solicitação",
	TABLE0.NMTITULO AS Título,
	REF0.NMIMPLEMENTACAO AS Implementação,
	REF1.NMLOCAL AS "Local de Fabricação",
	REF2.SEGMENTO AS SEGMENTO,
	REF3.TIPOFABRICACAO AS "Tipo de Fabricação",
	REF4.UNIDADE AS UNIDADE,
	WFACTIVITY.IDSTRUCT AS ATIVIDADE,
	REF5.CDPRODUTO AS "Código Do Produto Acabado",
	REF5.DSPRODUTO AS "Descrição Do Produto Acabado",
	REF6.CDPRODUTO AS "Código Do Produto Semi Acabado",
	REF6.DSPRODUTO AS "Descrição Do Produto Semi Acabado",
	REF7.CDPRODUTO AS "Código Componente",
	REF7.DSPRODUTO AS "Descrição do Componente",
	REF8.CDPRODUTO AS "Código Da Estrutura",
	REF8.DSPRODUTO AS "Descrição Da Estrutura",
	WFACTIVITY.DTESTIMATEDFINISH + (WFACTIVITY.NRTIMEESTFINISH * interval '1 minute') AS PRAZO_ATV,
	(
		CASE
			WHEN WFACTIVITY.FGSTATUS = 1 THEN '#{114667}' --A iniciar
			WHEN WFACTIVITY.FGSTATUS = 2 THEN '#{114666}' --Habilitado
			WHEN WFACTIVITY.FGSTATUS = 3 THEN '#{107507}' --Executado
			WHEN WFACTIVITY.FGSTATUS = 4 THEN '#{108240}' --Suspenso
			WHEN WFACTIVITY.FGSTATUS = 5 THEN '#{102338}' --Cancelado
			WHEN WFACTIVITY.FGSTATUS = 6 THEN '#{206049}' --Recusado
			WHEN WFACTIVITY.FGSTATUS = 7 THEN '#{214511}' -- Aprovação de retorno
		END
	) AS SITUACAO_ATIVIDADE,
	WFACTIVITY.DTEXECUTION + (WFACTIVITY.NRTIMEEXECUTION * interval '1 minute') AS DATA_EXECUCAO_ATIVIDADE,
	COALESCE(WFACTIVITY.NMUSER, WFACTIVITY.NMROLE) :: VARCHAR(255) AS RESPONSAVEL_ATIVIDADE,
	EXTRACT(
		DAY
		FROM
			(
				CURRENT_DATE - TO_TIMESTAMP(
					TO_CHAR(WFP.DTSTART, 'YYYY-MM-DD') || ' ' || WFP.TMSTART,
					'YYYY-MM-DD HH24:MI:SS'
				)
			)
	) AS DIAS_ATRASO,
	(
		CASE
			WHEN WFACTIVITY.FGCONCLUDEDSTATUS IS NOT NULL THEN CASE
				WHEN WFACTIVITY.FGCONCLUDEDSTATUS = 1 THEN 'Em dia'
				WHEN WFACTIVITY.FGCONCLUDEDSTATUS = 2 THEN 'Em atraso'
			END
			ELSE CASE
				WHEN WFACTIVITY.FGTYPE = 1 THEN --Só é necessário realizar as verificações abaixo com subselects, etc. se houver subprocesso. Como o processo CTC05 não possui subprocessos, o código abaixo não é necessário.
				--CASE WHEN ((SELECT WFPD.DTESTIMATEDFINISH FROM WFSTRUCT STRUCT INNER JOIN WFSUBPROCESS SUB ON STRUCT.IDOBJECT = SUB.IDOBJECT INNER JOIN WFPROCESS WFPD ON WFPD.IDOBJECT = SUB.IDSUBPROCESS WHERE STRUCT.IDOBJECT = WFACTIVITY.IDOBJECT) > CAST((CURRENT_DATE + INTERVAL '1 day') AS TIMESTAMP)
				--OR (		SELECT WFPD.DTESTIMATEDFINISH FROM WFSTRUCT STRUCT INNER JOIN WFSUBPROCESS SUB ON STRUCT.IDOBJECT = SUB.IDOBJECT INNER JOIN WFPROCESS WFPD ON WFPD.IDOBJECT = SUB.IDSUBPROCESS WHERE STRUCT.IDOBJECT = WFACTIVITY.IDOBJECT) IS NULL) 
				--	THEN 'Em dia' 
				--WHEN (( SELECT WFPD.DTESTIMATEDFINISH 	FROM WFSTRUCT STRUCT INNER JOIN WFSUBPROCESS SUB ON STRUCT.IDOBJECT = SUB.IDOBJECT INNER JOIN WFPROCESS WFPD ON WFPD.IDOBJECT = SUB.IDSUBPROCESS WHERE STRUCT.IDOBJECT = WFACTIVITY.IDOBJECT) = CAST(CURRENT_DATE AS TIMESTAMP) 
				--AND (	SELECT WFPD.NRTIMEESTFINISH 	FROM WFSTRUCT STRUCT INNER JOIN WFSUBPROCESS SUB ON STRUCT.IDOBJECT = SUB.IDOBJECT INNER JOIN WFPROCESS WFPD ON WFPD.IDOBJECT = SUB.IDSUBPROCESS WHERE STRUCT.IDOBJECT = WFACTIVITY.IDOBJECT) >= (EXTRACT(MINUTE FROM CURRENT_TIMESTAMP) + EXTRACT(HOUR FROM CURRENT_TIMESTAMP) * 60)) 
				--OR ((	SELECT WFPD.DTESTIMATEDFINISH 	FROM WFSTRUCT STRUCT INNER JOIN WFSUBPROCESS SUB ON STRUCT.IDOBJECT = SUB.IDOBJECT INNER JOIN WFPROCESS WFPD ON WFPD.IDOBJECT = SUB.IDSUBPROCESS WHERE STRUCT.IDOBJECT = WFACTIVITY.IDOBJECT) = CAST((CURRENT_DATE + INTERVAL '1 day') AS TIMESTAMP)) 
				--	THEN 'Próximo do vencimento' 
				--ELSE 'Em atraso' 
				--END 
				'Em dia'
				ELSE CASE
					WHEN (
						WFACTIVITY.DTESTIMATEDFINISH > CAST((CURRENT_DATE + INTERVAL '1 day') AS TIMESTAMP)
						OR WFACTIVITY.DTESTIMATEDFINISH IS NULL
					) THEN 'Em dia'
					WHEN (
						WFACTIVITY.DTESTIMATEDFINISH = CAST((CURRENT_DATE + INTERVAL '1 day') AS TIMESTAMP)
					)
					OR (
						WFACTIVITY.DTESTIMATEDFINISH = CAST(CURRENT_DATE AS TIMESTAMP)
						AND WFACTIVITY.NRTIMEESTFINISH >= (
							EXTRACT(
								MINUTE
								FROM
									CURRENT_TIMESTAMP
							) + EXTRACT(
								HOUR
								FROM
									CURRENT_TIMESTAMP
							) * 60
						)
					) THEN 'Próximo do vencimento'
					ELSE 'Em atraso'
				END
			END
		END
	) AS ESTADOATV
FROM
	DYNdevctc05 TABLE0
	INNER JOIN GNASSOCFORMREG FORMREG ON FORMREG.OIDENTITYREG = TABLE0.OID
	INNER JOIN WFPROCESS WFP ON FORMREG.CDASSOC = WFP.CDASSOCREG
	AND WFP.IDPROCESSMODEL = 'DEV-CTC05'
	LEFT JOIN WFSTRUCT WFACTIVITY ON WFP.IDOBJECT = WFACTIVITY.IDPROCESS
	AND WFACTIVITY.FGTYPE IN(2, 3)
	LEFT JOIN DYNdevctc05impleme REF0 ON TABLE0.OIDABCFOZ82IGOXLDK = REF0.OID
	LEFT JOIN DYNdevctc05local REF1 ON TABLE0.OIDABC03WM7JRSW6HK = REF1.OID
	LEFT JOIN DYNconctb01seg REF2 ON TABLE0.OIDABC88NP5F5CWOTW = REF2.OID
	LEFT JOIN DYNdevctc05tipofab REF3 ON TABLE0.OIDABCEUNPYX4WNEV5 = REF3.OID
	LEFT JOIN DYNconctb01unid REF4 ON TABLE0.OIDABCQGQSQA0HEB0M = REF4.OID
	LEFT JOIN DYNdevctc05prodaca REF5 ON TABLE0.OID = REF5.OIDABCU9ATRDQ2HICV
	LEFT JOIN DYNdevctc05prodsem REF6 ON TABLE0.OID = REF6.OIDABC7YZRAWM760PP
	LEFT JOIN DYNdevctc05compone REF7 ON TABLE0.OID = REF7.OIDABCPZA0BQMILNI1
	LEFT JOIN DYNdevctc05estrutu REF8 ON TABLE0.OID = REF8.OIDABCUEAEXIK5149W
	LEFT JOIN ADUSER ADU ON ADU.CDUSER = WFP.CDUSERSTART
	LEFT JOIN GNREVISIONSTATUS GNRS ON WFP.CDSTATUS = GNRS.CDREVISIONSTATUS
	AND GNRS.IDREVISIONSTATUS <> 'ST-DEVCTC05-01'
